version: '3.4'

services:
  minidlna:
    container_name: minidlna
    image: carlosrabelo/minidlna:latest
    restart: always
    ports:
      - 8200:8200
    volumes:
      - ~/Videos:/opt
    network_mode: host
